name: 'Slack Notify kubernetes'
description: 'Notify about kubernetes deployments via Slack'
inputs:
  slack-access-token:
    description: 'Access token for Slack, used to match commit emails to usernames'
    required: true
  commit-url:
    description: 'Github commit URL'
    required: true
  commit-author-username:
    description: 'Github commit author username'
    required: true
  commit-author-email:
    description: 'Github commit author email'
    required: true
  commit-message:
    description: 'Github commit message'
    required: true
runs:
  using: 'node20'
  main: 'dist/index.js'
